version: '3.3'

services:
    nginx:
        container_name: "nginx-symfony-test"
        image: nginx:latest
        ports:
            - '80:80'
        depends_on:
            - php
            - postgres
        volumes:
            - ./:/var/www/html:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./var/logs/nginx/:/var/log/nginx:cached

    postgres:
      container_name: "postgres-symfony-test"
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=php-sy-test
      ports:
        - '5433:5432'
    #   volumes: 
    #     - /docker/postgres/db:/var/lib/postgresql/data

    php:
        container_name: "php-symfony-test"
        build: 
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - .:/var/www/html
            - ./var/logs/symfony:/var/www/symfony/var/logs:cached
            - ./docker/php-fpm/php-limit.ini:/usr/local/etc/php/conf.d/php-limit.ini

    storage:
        image: minio/minio:latest
        ports:
            - '9001:9000'
        environment:
            - MINIO_ACCESS_KEY=${S3_KEY}
            - MINIO_SECRET_KEY=${S3_SECRET}
        volumes:
            - ./var/s3:/data
        command: 'server /data'
    composer:
        image: composer:latest
        volumes:
            - .:/app

