event_index:
  path: /event
  controller: App\Controller\EventController::index
  methods: GET

event_get:
  path: /event/{id}
  controller: App\Controller\EventController::getOne
  methods: GET

event_create:
  path: /event
  controller: App\Controller\EventController::create
  methods: POST

event_update:
  path: /event/{id}
  controller: App\Controller\EventController::update
  methods: PUT

event_delete:
  path: /event/{id}/delete
  controller: App\Controller\EventController::delete
  methods: DELETE
